### PR TITLE
Add more modifiers

### PR DESCRIPTION
**Pull request by malashin**
Added modifiers from hoi4 wiki.
https://hoi4.paradoxwikis.com/Modifiers

I did not really dig in much into the code of cwtools, I only use the VS Code extension right now. I'm working on a HOI4 mod and intend to expand HOI4 cwtools config in the future, it's not just a one off PR. So if you'd like me to test it somehow before making those PRs, I'd would be grateful to receive a quick rundown on how to do it.

### CODE REVIEW

**Comment by malashin** [comment]
I'd like to point out this line here:
`alias[modifier:production_speed_<building>] = float`

I'm not 100% sure that `<building>` will be picked up here, but it's analogous to other similar stuff and you seem to track buildings.

**Comment by malashin** [comment]
> There's now a modifiers.cwt file which is a simpler list for the simple modifiers (and has their scope).

I'm not sure what the scopes in that file are supposed to do. I assume you try to limit the use of those modifier to the stated scopes only.

For example this one `planning_speed = country` is supposed to be used in `country` scope.

But in reality it can be use in `unit leader` scope:
```ruby
staff_office_plan = {
	name = ABILITY_STAFF_OFFICE_PLAN
	desc = ABILITY_STAFF_OFFICE_PLAN_DESC
	
	sound_effect = command_power_ability_defensive
	
	type = army_leader
	
	allowed = {
		is_border_war = no
	}
	
	cost = 0.12
	duration = 168
	
	unit_modifiers = {
		planning_speed = 4.0
	}
	
	
	ai_will_do = {
		factor = -1
		modifier = {
			FROM = {
				command_power > 2.0
			}
			check_variable = { num_units > 6 }
			check_variable = { unit_ratio_ready_for_plan > 0.55 }
			check_variable = { avg_unit_planning_ratio < 0.4 }
			
			add = 2
		}
	}
}
```

The parser recognizes that it is used in `unit leader` scope and there is no error, which is fine and the way it should be. But why have `planning_speed = country` in the `modifiers.cwt` file then?

**Comment by tboby** [comment]
It's not currently set up properly for HOI4, which is why it isn't checking scopes for modifiers yet. They're there so that I can start using them once I get it working. But I'll explain it using stellaris as an example:

It seems like there are more categories of modifier than there are types of scope. So in stellaris I have:
https://github.com/tboby/cwtools/blob/master/CWTools/Common/STLConstants.fs#L172
Stellaris has `setup.log`, a file which outputs all the modifiers and what modifier category they are. The above then maps from those categories to scopes.

So far I've got two modifier categories coded for HOI4:
- State
- Country
And from discussion I think there are at least:
- unit
- unit_leader
- air
as well.

While you can't scope to unit, there are definitely modifiers which apply at a unit level. (E.g. you can't use a unit_leader modifier in some modifier blocks).

They're all `country` by default when I created the file, so please feel free to change them to the most specific modifier category you think they have.

**Comment by malashin** [comment]
What if modifier can be applied to several different scopes?

Not 100% sure, but as in the previous example `planning_speed` was a part of `unit_leader`'s scope. But I think you can get an adviser giving `planning_speed` in a `country` scope.

**Comment by tboby** [comment]
Yup, that's why I have modifier categories as separate from scopes. So, in Stellaris:
`        ModifierCategory.Leader, [Scope.Leader; Scope.Country]`
A "Leader" modifier can be applied in both Leader and Country scopes

**Comment by tboby** [comment]
@malashin I've released v0.6.21 of cwtools-vscode, which validates correct scopes for HOI4 modifiers.
I added aces.cwt to master. If you try using country modifiers in an aces effect you'll see it doesn't let you :)
I'm not quite sure what modifiers are allowed where in places like traits however.

**Comment by malashin** [comment]
I'd like to clarify some things.

As I see it now, the idea is to:

- Have all modifiers and their respective scopes assigned in `modifiers.cwt`.
- Use `temp_modifiers.cwt` for complicated generated modifiers like `local_resources_<resource>`.

Some issues I see in that approach:

- `modifiers.cwt` should accept several scopes instead of just one. Just allowing country modifiers in unit_leader scope is not really an ideal solution, though it will save quite a lot of time. And this is not currently implemented in HOI4 config, country modifiers return error if found in unit_leader scope atm.
- `modifiers.cwt` loses strict variable types assignment that `temp_modifiers.cwt` has. Though it seems like every number is a float in CW engine, I'm not sure how this is handled.
- `temp_modifiers.cwt` does not have scope checks.

What I'd like to see implemented, in order of importance. Syntax is up to you.

1. Assigning several scopes to one modifier:
```ruby
dig_in_speed = { country, unit_leader }
```
2. Strict type assignment:
```ruby
dig_in_speed = {
	scopes =  { country, unit_leader }
	type = float
}
```

If this is too complicated to do, we at least need to allow country modifiers in unit_leader scopes.
You seem to have most of the modifiers implemented right now. I'll take a closer look and assign the needed scopes ones this is sorted.

**Comment by tboby** [comment]
> Have all modifiers and their respective scopes assigned in `modifiers.cwt`

Almost, have all modifiers and their **modifier category** assigned in `modifiers.cwt`
> Use temp_modifiers.cwt for complicated generated modifiers like local_resources_<resource>.

With their required **scopes**.

As far as I know you can always use a modifier in a "higher" scope. Unit_leader modifiers can be used in country. So:

```modifiers = { 
dig_in_speed = unit_leader 
naval_strike_targetting_factor = air
}```

would be the same as

```
## scopes = { unit_leader country }
alias[modifier:dig_in_speed] = float

##scopes = { air country }
alias[modifier:naval_strike_targetting_factor] = float
```

> modifiers.cwt loses strict variable types assignment that temp_modifiers.cwt has. Though it seems like every number is a float in CW engine, I'm not sure how this is handled.

This is a good point. `modifiers.cwt` get mapped to `float` with a range of `-1E+12, 1E+12`.

The problem is that PDX games don't use integers or floats, they use fixed point numbers. So normally you can use `1.0` instead of `1` which is a bit tricky for cwtools.

If we want to do this properly, maybe the right hand side should become a normal rule value:
```
modifiers = {
    ## modifier_category = unit_leader
    dig_in_speed = int
    ## modifier_category = air
    naval_strike_targetting_factor = float[-1000,1000]
}
```

**Comment by malashin** [comment]
It looks like `modifiers.cwt` is not picked up from local config rules from mods `.cwtools` folder.
It says that the modifier is supposed to be in country scope no matter what I change it to, even if I remove that modifier from the file.

cwtools_modifier_rules

Updating this two files and reloading the rules worked fine.
```
\common\abilities.cwt
variables.cwt
```

**Pull request closed without merging**
